import type Stripe from 'stripe';

/** Keep these in sync with @temporal-stripe/core — duplicated here so the
 *  webhook package has zero runtime dependency on core. */
export const REAUTHORIZATION_METADATA_KEY = 'canceledBy';
export const REAUTHORIZATION_METADATA_VALUE = 'reauthorization-workflow';

const NON_CUSTOMER_CANCEL_REASONS = new Set<string>([
  'automatic',
  'expired',
  'failed_invoice',
  'void_invoice',
]);

/**
 * True when this `payment_intent.canceled` event was generated by the
 * reauthorization workflow tagging-and-canceling the old PI. Consumers should
 * short-circuit their cancel-handling logic on this signal.
 */
export function isReauthorizationCancel(event: Stripe.Event): boolean {
  if (event.type !== 'payment_intent.canceled') return false;
  const pi = event.data.object as Stripe.PaymentIntent;
  const tag = pi.metadata?.[REAUTHORIZATION_METADATA_KEY];
  return tag === REAUTHORIZATION_METADATA_VALUE;
}

/**
 * True when the cancellation was Stripe-initiated (expired auth, failed invoice,
 * void invoice) rather than a customer / merchant action. Most consumers want
 * to ignore these for their "order canceled" logic too.
 */
export function isStripeInitiatedCancel(event: Stripe.Event): boolean {
  if (event.type !== 'payment_intent.canceled') return false;
  const pi = event.data.object as Stripe.PaymentIntent;
  const reason = pi.cancellation_reason ?? '';
  return NON_CUSTOMER_CANCEL_REASONS.has(reason);
}

/**
 * Convenience: returns true when the consumer should treat this event as a
 * genuine customer/merchant cancellation. Use as the inverse:
 *
 *   if (event.type === 'payment_intent.canceled' && !shouldRouteToCancelHandler(event)) return;
 */
export function shouldRouteToCancelHandler(event: Stripe.Event): boolean {
  if (event.type !== 'payment_intent.canceled') return false;
  return !isReauthorizationCancel(event) && !isStripeInitiatedCancel(event);
}

/**
 * Functional helper for express/fastify-style handler chains. Returns the
 * event unchanged if it should be processed, `null` if it should be skipped.
 */
export function filterReauthorizationCancels(
  event: Stripe.Event,
): Stripe.Event | null {
  if (event.type === 'payment_intent.canceled' && isReauthorizationCancel(event)) {
    return null;
  }
  return event;
}
